strategy: configs/training-single.yaml
num_workers: 4 # as large as possible
augmentation_prob: 0.25
augmentation_types:
   - fog
   - noise
   - gaussian_blur
   - color_jitter
   - horizontal_flip
   - rain_effect
horizontal_flip_prob: 0.5
model_type: baseline
decay_coefficient: 30
debug: False
print_freq: 4
training_dir: dataset/sliding_window/train
training_csv: dataset/sliding_window/train_extracted_clips.csv
validation_dir: dataset/sliding_window/validation
validation_csv: dataset/sliding_window/validation_extracted_clips.csv
evaluation_dir: dataset/sliding_window/evaluation/
evaluation_csv: dataset/sliding_window/validation_videos.csv
evaluation_train_dir: dataset/sliding_window/evaluation-train/
evaluation_train_csv: dataset/sliding_window/train_videos.csv