strategy: configs/training-unfreeze_all.yaml
num_workers: 8 # as large as possible
seed: 123
augmentation_prob: 0.25
augmentation_types:
   - fog
   - noise
   - gaussian_blur
   - color_jitter
   - horizontal_flip
   - rain_effect
horizontal_flip_prob: 0.5
model_type: baseline
debug: False
print_freq: 16
training_dir: dataset/image/train/ #dataset/sliding_window/train
training_csv: dataset/frame_train.csv #dataset/sliding_window/train_extracted_clips.csv
validation_dir: dataset/image/validation/ #dataset/sliding_window/validation
validation_csv: dataset/frame_validation.csv #dataset/sliding_window/validation_extracted_clips.csv
evaluation_dir: dataset/sliding_window/evaluation/
evaluation_csv: dataset/sliding_window/validation_videos.csv
evaluation_train_dir: dataset/sliding_window/evaluation-train/
evaluation_train_csv: dataset/sliding_window/train_videos.csv
num_train_samples: 1200