batch_size: 10
learning_rate: 0.0001
epochs: 20
num_workers: 8 # as large as possible
augmentation_prob: 0.25
augmentation_types:
   - fog
   - noise
   - gaussian_blur
   - color_jitter
   - horizontal_flip
   - rain_effect
horizontal_flip_prob: 0.5
model_type: baseline
optimizer: radam
decay_coefficient: 30
debug: False
print_freq: 4
model_dir: sliding_window
monitor_dir: sliding_window_monitor #In this directory, the numerical results of metrics will be saved per training epoch.
training_dir: dataset/sliding_window/train
training_csv: dataset/sliding_window/train_extracted_clips.csv
validation_dir: dataset/sliding_window/validation
validation_csv: dataset/sliding_window/validation_extracted_clips.csv
evaluation_dir: dataset/sliding_window/evaluation/
evaluation_csv: dataset/sliding_window/validation_videos.csv
