training_strategy: configs/training.yaml 
seed: 123
augmentation_prob: 0 #
augmentation_types: #
horizontal_flip_prob: 0.
model_type: baseline
debug: False
print_freq: 16
training_dir: dataset/image/train
#dataset/sliding_window/train
training_csv: dataset/frame_train.csv #dataset/sliding_window/train_extracted_clips.csv
validation_dir: dataset/image/validation/ #dataset/sliding_window/validation
validation_csv: dataset/frame_validation.csv #dataset/sliding_window/validation_extracted_clips.csv
evaluation_dir: dataset/sliding_window/evaluation/
evaluation_csv: dataset/sliding_window/validation_videos.csv
evaluation_train_dir: dataset/sliding_window/evaluation-train/
evaluation_train_csv: dataset/sliding_window/train_videos.csv
num_train_samples: 1200
scheduler:
  name: CosineAnnealingLR #options: 
  eta_min: 1e-6
  #name: ReduceLROnPlateau
  #mode: min
  #factor: 0.5
  #patience: 3
  #min_lr: 1e-6
total_epochs: 30
#classifier: 