strategy: single #single
batch_size: 10
resume: True # If True, the model will load parameters from `check_point_path`
optim_resume: False # If True, the optimizer will load saved state from `optim_check_point_path` 
optimizer:
  name: adamw
  lr: 1e-5
  weight_decay: 1e-4
scheduler:
  name: CosineAnnealingLR #options: 
  T_max: 10
  eta_min: 1e-7
  #name: ReduceLROnPlateau
  #mode: min
  #factor: 0.5
  #patience: 3
  #min_lr: 1e-6
epochs: 30
model_dir: benmark_single # will store the trained checkpoint under this folder
monitor_dir: benmark_single-monitor # will store the metric points under this. Currently, this will be overwritten by a new training process.
trainable_parts: ["layer3", "layer4", "classifier"] # options: ["*"], ["classifier"], ["layer4", "classifier"]
check_point_path: benmark_single_FreezeDeepLayer/model_ckpt-epoch01_bs10_lr1e-4_aug0.25_col_fog_gau_hor_noi_rai.pt #valid only if resume is True
optim_check_point_path: #valid only if optim_resume is True